DROP DATABASE IF EXISTS tracker_db;
CREATE DATABASE tracker_db;
USE tracker_db; 

CREATE TABLE employee (
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30),
last_name VARCHAR(30),
role_id INTEGER,
manager_id INTEGER,
);

CREATE TABLE department (
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
department_name VARCHAR(30),
);

CREATE TABLE role (
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30),
salary INTEGER (8,2),
department_id INTEGER,
);